### PR TITLE
Table.count duplicate

### PR DESCRIPTION
**Pull request by Stooberton**
Removed instance of table being counted 3 times
Replaced with ipairs loop and updated var references ( `Targets[I]` -> `Target` )

### CODE REVIEW

**Comment by Dakota0001** [comment]
These changes appear to be heavily conflicting in over 40 places with the current code, you seem to be pulling from a very outdated branch.

**Comment by Stooberton** [comment]
Its up to date. It must be complaining about the whitespace change.

**Comment by Dakota0001** [comment]
the whitespace change is where most of the problems are, but I looked at the conflicts involved and there's a lot of missing code in your commit, thus why it seems like it is outdated.

**Comment by Stooberton** [comment]
You're right, actually! Weird, I have no idea how that happened. My bad.

**Pull request closed without merging**
